import {
  createSystemRoles,
  OWNER_DISPLAY_NAME,
  OWNER_USER_ID,
  PORTAL_OWNER_AUTH_EMAIL,
  SYSTEM_ROLE_IDS,
} from "../domain/permissions";
import { DEFAULT_INVENTORY_SETTINGS } from "../domain/inventory";
import { defaultOpsApprovalRules } from "../domain/ops-hub";
import type { TlbState } from "../domain/types";
import { DEFAULT_AGEING, DEFAULT_COMPANY, DEFAULT_VAT } from "./migrate";

const NOW = "2026-09-09T09:00:00.000Z";
const EARLIER = "2026-09-02T10:00:00.000Z";
/** Extra commercial dates so dashboard period filters diverge visibly. */
const TODAY_AM = "2026-09-09T08:15:00.000Z";
const THIS_WEEK = "2026-09-08T11:30:00.000Z";
const THIS_QUARTER = "2026-08-14T09:00:00.000Z";
const PREV_MONTH_LATE = "2026-08-28T14:20:00.000Z";
const THIS_YEAR = "2026-03-18T10:00:00.000Z";

/** Seed includes Phase 30 Chemical A/B scenario ready to demo. */
export function createSeedState(): TlbState {
  const roles = createSystemRoles();
  return {
    version: 14,
    currentUserId: OWNER_USER_ID,
    currentUser: OWNER_DISPLAY_NAME,
    currentRoleId: SYSTEM_ROLE_IDS.Owner,
    currentRole: "Owner",
    roles,
    users: [
      {
        id: OWNER_USER_ID,
        name: OWNER_DISPLAY_NAME,
        email: PORTAL_OWNER_AUTH_EMAIL,
        roleId: SYSTEM_ROLE_IDS.Owner,
        active: true,
      },
      {
        id: "user-sales",
        name: "Ama Mensah",
        email: "sales@tlb.gh",
        roleId: SYSTEM_ROLE_IDS.Sales,
        active: true,
      },
      {
        id: "user-warehouse",
        name: "Kofi Boateng",
        email: "warehouse@tlb.gh",
        roleId: SYSTEM_ROLE_IDS.Warehouse,
        active: true,
      },
      {
        id: "user-finance",
        name: "Efua Addo",
        email: "finance@tlb.gh",
        roleId: SYSTEM_ROLE_IDS.Finance,
        active: true,
      },
      {
        id: "user-manager",
        name: "Yaw Mensah",
        email: "manager@tlb.gh",
        roleId: SYSTEM_ROLE_IDS.Manager,
        active: true,
      },
      {
        id: "user-driver",
        name: "Kwesi Owusu",
        email: "driver@tlb.gh",
        roleId: SYSTEM_ROLE_IDS.Driver,
        active: true,
      },
      {
        id: "user-requester",
        name: "Abena Factory",
        email: "factory@tlb.gh",
        roleId: SYSTEM_ROLE_IDS.Requester,
        active: true,
      },
    ],
    ageing: { ...DEFAULT_AGEING },
    company: { ...DEFAULT_COMPANY },
    vatRates: DEFAULT_VAT.map((v) => ({ ...v })),
    counters: {
      order: 124,
      supply: 124,
      customer: 3,
      supplier: 3,
      supplierPo: 5,
      supplierReceipt: 5,
      supplierPayment: 4,
      invoice: 124,
      receipt: 124,
      delivery: 124,
      payment: 124,
      quotation: 124,
      stockMovement: 6,
      stockIssue: 0,
      transfer: 1,
      adjustment: 0,
      batch: 4,
      customerReturn: 1,
      supplierReturn: 1,
      nonPoPurchase: 1,
      importShipment: 2,
      exportShipment: 1,
      opsRequest: 124,
    },
    opsRequests: [],
    opsRequestLines: [],
    opsDrivers: [
      {
        id: "drv-kwesi",
        code: "DRV-01",
        name: "Kwesi Owusu",
        phone: "+233 24 555 0101",
        vehicle: "GN-4521-21",
        active: true,
        userId: "user-driver",
      },
      {
        id: "drv-ama",
        code: "DRV-02",
        name: "Ama Darko",
        phone: "+233 20 555 0202",
        vehicle: "GR-8890-20",
        active: true,
      },
    ],
    opsMessages: [],
    opsActivity: [],
    opsCustody: [],
    opsDiscrepancies: [],
    opsApprovalRules: defaultOpsApprovalRules(),
    inventorySettings: { ...DEFAULT_INVENTORY_SETTINGS },
    quotations: [],
    customerReturns: [
      {
        id: "crt-seed-1",
        number: "TLB-CRT-2609-00001",
        customerId: "cus-demo",
        orderId: "ord-phase30",
        productId: "prod-hcl",
        batchId: "bat-hcl-26001",
        quantity: 1,
        reason: "Drum seal damaged in transit",
        condition: "Damaged",
        warehouseId: "wh-main",
        disposition: "quarantine",
        status: "Posted",
        receivedBy: "TLB Owner",
        receivedAt: THIS_WEEK,
        approvedBy: "TLB Owner",
        approvedAt: THIS_WEEK,
        notes: "Seed customer return for demo",
        createdAt: THIS_WEEK,
      },
    ],
    supplierReturns: [
      {
        id: "srt-seed-1",
        number: "TLB-SRT-2609-00001",
        supplierId: "sup-ningbo",
        productId: "prod-eth",
        batchId: undefined,
        quantity: 1,
        reason: "Off-spec assay on receipt QC",
        creditNoteRef: "CN-SEED-01",
        replacementExpected: false,
        status: "Credited",
        warehouseId: "wh-main",
        requestedBy: "TLB Owner",
        requestedAt: PREV_MONTH_LATE,
        approvedBy: "TLB Owner",
        approvedAt: PREV_MONTH_LATE,
        notes: "Seed supplier return",
        createdAt: PREV_MONTH_LATE,
      },
    ],
    nonPoPurchases: [
      {
        id: "npo-seed-1",
        number: "TLB-NPO-2609-00001",
        supplierId: "sup-ningbo",
        warehouseId: "wh-main",
        reason: "Urgent lab solvent top-up — no open PO",
        status: "Pending Approval",
        requestedBy: "TLB Owner",
        requestedAt: TODAY_AM,
        invoiceRef: "INV-URG-441",
        notes: "Seed Non-PO awaiting approval",
        createdAt: TODAY_AM,
      },
    ],
    nonPoPurchaseLines: [
      {
        id: "npol-seed-1",
        nonPoId: "npo-seed-1",
        productId: "prod-eth",
        quantity: 2,
        unitPrice: 420,
        batchCode: "ETH-NPO-01",
      },
    ],
    importShipments: [
      {
        id: "imp-seed-1",
        number: "TLB-IMP-2609-00001",
        supplierId: "sup-ningbo",
        originCountry: "China",
        purchaseOrderId: "spo-hcl-trace",
        containerRef: "MSCU-7788123",
        shippingLine: "MSC",
        orderedAt: THIS_QUARTER,
        etd: "2026-08-20",
        eta: "2026-09-12",
        clearanceNotes: "HS code chemicals · Tema port",
        customsDocs: "BOE-SEP-991",
        warehouseId: "wh-main",
        status: "Clearance",
        freightCost: 4800,
        dutyCost: 1200,
        notes: "HCl import container",
        createdBy: "TLB Owner",
        createdAt: THIS_QUARTER,
        updatedAt: TODAY_AM,
      },
      {
        id: "imp-seed-2",
        number: "TLB-IMP-2608-00002",
        supplierId: "sup-tema-drum",
        originCountry: "India",
        containerRef: "TGHU-441190",
        shippingLine: "Maersk",
        orderedAt: PREV_MONTH_LATE,
        etd: "2026-08-10",
        eta: "2026-08-28",
        warehouseId: "wh-main",
        status: "Warehouse Received",
        freightCost: 2100,
        dutyCost: 600,
        receivedAt: PREV_MONTH_LATE,
        createdBy: "TLB Owner",
        createdAt: PREV_MONTH_LATE,
        updatedAt: PREV_MONTH_LATE,
      },
    ],
    importShipmentLines: [
      {
        id: "impl-1",
        shipmentId: "imp-seed-1",
        productId: "prod-hcl",
        quantity: 40,
        unitCost: 610,
      },
      {
        id: "impl-2",
        shipmentId: "imp-seed-2",
        productId: "prod-chem-a",
        quantity: 10,
        unitCost: 800,
      },
    ],
    exportShipments: [
      {
        id: "exp-seed-1",
        number: "TLB-EXP-2609-00001",
        customerId: "cus-apex",
        destinationCountry: "Cote d'Ivoire",
        carrier: "Bollore Logistics",
        docsRef: "EXP-CI-220",
        status: "Preparing",
        staffName: "Kofi Boateng",
        notes: "Regional distributor consignment",
        createdAt: TODAY_AM,
        updatedAt: TODAY_AM,
      },
    ],
    exportShipmentLines: [
      {
        id: "expl-1",
        shipmentId: "exp-seed-1",
        productId: "prod-chem-b",
        quantity: 2,
      },
    ],
    warehouses: [
      {
        id: "wh-main",
        code: "MAIN",
        name: "Main Warehouse",
        location: "Tema · bonded chemicals",
        active: true,
      },
      {
        id: "wh-factory",
        code: "FACTORY",
        name: "Factory Store",
        location: "Production floor · WIP",
        active: true,
      },
      {
        id: "wh-accra",
        code: "ACCRA",
        name: "Accra Hub",
        location: "Accra · regional fulfilment",
        active: true,
      },
    ],
    products: [
      {
        id: "prod-chem-a",
        sku: "CHEM-A",
        name: "Chemical A",
        unit: "drums",
        category: "Raw chemical",
        active: true,
        issueStrategy: "FEFO",
        reorderPoint: 4,
        reorderQty: 10,
        minQty: 2,
        maxQty: 40,
        standardCost: 850,
        preferredSupplierId: "sup-ningbo",
        leadTimeDays: 21,
      },
      {
        id: "prod-chem-b",
        sku: "CHEM-B",
        name: "Chemical B",
        unit: "drums",
        category: "Raw chemical",
        active: true,
        issueStrategy: "FIFO",
        reorderPoint: 8,
        reorderQty: 20,
        standardCost: 920,
        preferredSupplierId: "sup-ningbo",
        leadTimeDays: 18,
      },
      {
        id: "prod-mat-b",
        sku: "MAT-B",
        name: "Material B",
        unit: "bags",
        category: "Raw material",
        active: true,
        issueStrategy: "FEFO",
        reorderPoint: 10,
        reorderQty: 25,
        standardCost: 140,
        preferredSupplierId: "sup-ningbo",
        leadTimeDays: 10,
      },
      {
        id: "prod-hcl",
        sku: "CHEM-001",
        name: "Hydrochloric Acid 32%",
        unit: "drums",
        category: "Acid",
        active: true,
        issueStrategy: "FEFO",
        reorderPoint: 40,
        reorderQty: 80,
        minQty: 20,
        maxQty: 400,
        standardCost: 640,
        preferredSupplierId: "sup-ningbo",
        leadTimeDays: 30,
      },
      {
        id: "prod-eth",
        sku: "CHEM-014",
        name: "Ethanol 96%",
        unit: "drums",
        category: "Solvent",
        active: true,
        issueStrategy: "FEFO",
        reorderPoint: 12,
        reorderQty: 24,
        standardCost: 1250,
        leadTimeDays: 14,
      },
    ],
    stock: [
      {
        id: "stk-a-main",
        productId: "prod-chem-a",
        warehouseId: "wh-main",
        physicalQty: 2,
        reservedQty: 0,
        damagedQty: 0,
        expiredQty: 0,
        quarantineQty: 0,
        inTransitQty: 0,
        allocatedQty: 0,
      },
      {
        id: "stk-b-main",
        productId: "prod-chem-b",
        warehouseId: "wh-main",
        physicalQty: 25,
        reservedQty: 0,
        damagedQty: 0,
        expiredQty: 0,
        quarantineQty: 0,
        inTransitQty: 0,
        allocatedQty: 0,
      },
      {
        id: "stk-matb-main",
        productId: "prod-mat-b",
        warehouseId: "wh-main",
        physicalQty: 15,
        reservedQty: 0,
        damagedQty: 0,
        expiredQty: 0,
        quarantineQty: 0,
        inTransitQty: 0,
        allocatedQty: 0,
      },
      {
        id: "stk-matb-accra",
        productId: "prod-mat-b",
        warehouseId: "wh-accra",
        physicalQty: 40,
        reservedQty: 0,
        damagedQty: 0,
        expiredQty: 0,
        quarantineQty: 0,
        inTransitQty: 0,
        allocatedQty: 0,
      },
      {
        id: "stk-hcl-main",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        physicalQty: 200,
        reservedQty: 12,
        damagedQty: 2,
        expiredQty: 0,
        quarantineQty: 0,
        inTransitQty: 0,
        allocatedQty: 0,
      },
      {
        id: "stk-eth-main",
        productId: "prod-eth",
        warehouseId: "wh-main",
        physicalQty: 48,
        reservedQty: 0,
        damagedQty: 0,
        expiredQty: 0,
        quarantineQty: 0,
        inTransitQty: 0,
        allocatedQty: 0,
      },
      {
        id: "stk-hcl-fac",
        productId: "prod-hcl",
        warehouseId: "wh-factory",
        physicalQty: 40,
        reservedQty: 0,
        damagedQty: 0,
        expiredQty: 0,
        quarantineQty: 0,
        inTransitQty: 0,
        allocatedQty: 0,
      },
    ],
    batches: [
      {
        id: "bat-hcl-26022",
        code: "HCL-26022",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        supplierId: "sup-ningbo",
        receivedQty: 180,
        remainingQty: 140,
        unitCost: 610,
        manufacturedAt: "2026-06-01",
        expiresAt: "2027-06-01",
        receivedAt: THIS_QUARTER,
        grnId: "grn-hcl-trace",
        supplierPoId: "spo-hcl-trace",
        status: "Open",
        notes: "Primary FEFO batch for HCl traceability demo.",
      },
      {
        id: "bat-hcl-26001",
        code: "HCL-26001",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        supplierId: "sup-ningbo",
        receivedQty: 60,
        remainingQty: 40,
        unitCost: 640,
        manufacturedAt: "2025-12-01",
        expiresAt: "2026-10-15",
        receivedAt: THIS_YEAR,
        grnId: "grn-hcl-old",
        supplierPoId: "spo-hcl-trace",
        status: "Open",
        notes: "Earlier batch — expires within 90 days.",
      },
      {
        id: "bat-matb-main",
        code: "MATB-26001",
        productId: "prod-mat-b",
        warehouseId: "wh-main",
        supplierId: "sup-ningbo",
        receivedQty: 15,
        remainingQty: 15,
        unitCost: 140,
        manufacturedAt: "2026-07-01",
        expiresAt: "2027-07-01",
        receivedAt: THIS_WEEK,
        status: "Open",
        notes: "Material B FEFO lot — Main.",
      },
      {
        id: "bat-matb-accra",
        code: "MATB-ACC-01",
        productId: "prod-mat-b",
        warehouseId: "wh-accra",
        supplierId: "sup-ningbo",
        receivedQty: 40,
        remainingQty: 40,
        unitCost: 135,
        manufacturedAt: "2026-08-01",
        expiresAt: "2027-08-01",
        receivedAt: TODAY_AM,
        status: "Open",
        notes: "Accra hub can fulfil Material B.",
      },
      {
        id: "bat-hcl-fac",
        code: "HCL-FAC-40",
        productId: "prod-hcl",
        warehouseId: "wh-factory",
        supplierId: "sup-ningbo",
        receivedQty: 40,
        remainingQty: 40,
        unitCost: 610,
        manufacturedAt: "2026-06-01",
        expiresAt: "2027-06-01",
        receivedAt: PREV_MONTH_LATE,
        grnId: "grn-hcl-trace",
        status: "Open",
        notes: "Transferred portion sitting at Factory Store.",
      },
    ],
    goodsReceipts: [
      {
        id: "grn-hcl-trace",
        number: "TLB-GRN-2608-00005",
        supplierId: "sup-ningbo",
        purchaseOrderId: "spo-hcl-trace",
        nonPo: false,
        status: "Approved",
        receivedAt: THIS_QUARTER,
        receivedBy: "Kofi Boateng",
        checkedBy: "Kofi Boateng",
        checkedAt: THIS_QUARTER,
        approvedBy: "TLB Owner",
        approvedAt: THIS_QUARTER,
        warehouseId: "wh-main",
        documentRefs: "BL-NING-8841 · COA-HCL-26022",
        notes: "Traceability seed GRN for Hydrochloric Acid 32%.",
        createdAt: THIS_QUARTER,
      },
      {
        id: "grn-hcl-old",
        number: "TLB-GRN-2603-00006",
        supplierId: "sup-ningbo",
        purchaseOrderId: "spo-hcl-trace",
        nonPo: false,
        status: "Approved",
        receivedAt: THIS_YEAR,
        receivedBy: "Kofi Boateng",
        approvedBy: "TLB Owner",
        approvedAt: THIS_YEAR,
        warehouseId: "wh-main",
        notes: "Earlier HCl intake.",
        createdAt: THIS_YEAR,
      },
    ],
    goodsReceiptLines: [
      {
        id: "grnl-1",
        grnId: "grn-hcl-trace",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        batchCode: "HCL-26022",
        orderedQty: 200,
        acceptedQty: 180,
        rejectedQty: 18,
        damagedQty: 2,
        unitCost: 610,
        manufacturedAt: "2026-06-01",
        expiresAt: "2027-06-01",
        batchId: "bat-hcl-26022",
      },
      {
        id: "grnl-2",
        grnId: "grn-hcl-old",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        batchCode: "HCL-26001",
        orderedQty: 60,
        acceptedQty: 60,
        rejectedQty: 0,
        damagedQty: 0,
        unitCost: 640,
        manufacturedAt: "2025-12-01",
        expiresAt: "2026-10-15",
        batchId: "bat-hcl-26001",
      },
    ],
    stockMovements: [
      {
        id: "mv-open-hcl",
        number: "TLB-MV-2603-00001",
        type: "opening",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        batchId: "bat-hcl-26001",
        qtyBefore: 0,
        qtyMove: 60,
        qtyAfter: 60,
        signedQty: 60,
        reason: "Opening balance",
        actor: "TLB Owner",
        at: THIS_YEAR,
      },
      {
        id: "mv-grn-hcl",
        number: "TLB-MV-2608-00002",
        type: "grn",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        batchId: "bat-hcl-26022",
        qtyBefore: 60,
        qtyMove: 180,
        qtyAfter: 240,
        signedQty: 180,
        refType: "grn",
        refId: "grn-hcl-trace",
        refNumber: "TLB-GRN-2608-00005",
        actor: "Kofi Boateng",
        at: THIS_QUARTER,
      },
      {
        id: "mv-tr-out",
        number: "TLB-MV-2608-00003",
        type: "transfer_out",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        batchId: "bat-hcl-26022",
        qtyBefore: 240,
        qtyMove: 40,
        qtyAfter: 200,
        signedQty: -40,
        refType: "transfer",
        refId: "tr-hcl-fac",
        refNumber: "TLB-TR-2608-00001",
        actor: "Kofi Boateng",
        at: PREV_MONTH_LATE,
      },
      {
        id: "mv-tr-in",
        number: "TLB-MV-2608-00004",
        type: "transfer_in",
        productId: "prod-hcl",
        warehouseId: "wh-factory",
        batchId: "bat-hcl-fac",
        qtyBefore: 0,
        qtyMove: 40,
        qtyAfter: 40,
        signedQty: 40,
        refType: "transfer",
        refId: "tr-hcl-fac",
        refNumber: "TLB-TR-2608-00001",
        actor: "Kofi Boateng",
        at: PREV_MONTH_LATE,
      },
      {
        id: "mv-dmg",
        number: "TLB-MV-2608-00005",
        type: "damage",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        qtyBefore: 200,
        qtyMove: 2,
        qtyAfter: 200,
        signedQty: 0,
        reason: "Damaged drums quarantined on receipt (physical already net of damage bucket)",
        notes: "Damaged qty tracked in stock.damagedQty",
        actor: "Kofi Boateng",
        at: THIS_QUARTER,
      },
      {
        id: "mv-open-a",
        number: "TLB-MV-2609-00006",
        type: "opening",
        productId: "prod-chem-a",
        warehouseId: "wh-main",
        qtyBefore: 0,
        qtyMove: 2,
        qtyAfter: 2,
        signedQty: 2,
        reason: "Phase 30 starting stock",
        actor: "TLB Owner",
        at: EARLIER,
      },
    ],
    stockIssues: [],
    stockIssueLines: [],
    transfers: [
      {
        id: "tr-hcl-fac",
        number: "TLB-TR-2608-00001",
        fromWarehouseId: "wh-main",
        toWarehouseId: "wh-factory",
        status: "Received",
        requestedAt: PREV_MONTH_LATE,
        requestedBy: "Kofi Boateng",
        approvedAt: PREV_MONTH_LATE,
        approvedBy: "TLB Owner",
        releasedAt: PREV_MONTH_LATE,
        releasedBy: "Kofi Boateng",
        inTransitAt: PREV_MONTH_LATE,
        receivedAt: PREV_MONTH_LATE,
        receivedBy: "Kofi Boateng",
        notes: "Move HCl drums to Factory Store for dilution runs.",
      },
    ],
    transferLines: [
      {
        id: "trl-1",
        transferId: "tr-hcl-fac",
        productId: "prod-hcl",
        batchId: "bat-hcl-26022",
        quantity: 40,
      },
    ],
    adjustments: [],
    adjustmentLines: [],
    approvals: [
      {
        id: "appr-tr-1",
        kind: "transfer",
        status: "Approved",
        title: "Transfer TLB-TR-2608-00001",
        summary: "Main → Factory HCl transfer",
        refType: "transfer",
        refId: "tr-hcl-fac",
        requestedAt: PREV_MONTH_LATE,
        requestedBy: "Kofi Boateng",
        decidedAt: PREV_MONTH_LATE,
        decidedBy: "TLB Owner",
      },
      {
        id: "appr-npo-1",
        kind: "non_po_purchase",
        status: "Pending",
        title: "Non-PO TLB-NPO-2609-00001",
        summary: "Urgent lab solvent top-up — no open PO",
        refType: "non_po_purchase",
        refId: "npo-seed-1",
        amount: 840,
        requestedAt: TODAY_AM,
        requestedBy: "TLB Owner",
      },
    ],
    customers: [
      {
        id: "cus-demo",
        code: "TLB-CUS-0001",
        name: "Demo Chemical Labs",
        category: "Laboratory",
        contactName: "Ama Mensah",
        phone: "+233 24 555 0101",
        email: "ama@demochem.gh",
        address: "12 Spintex Road, Accra",
        tin: "C0001234567",
        creditLimit: 250000,
        paymentTerms: "Net 30",
        notes: "Phase 30 demo customer for partial supply workflow.",
        active: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
      {
        id: "cus-korle",
        code: "TLB-CUS-0002",
        name: "Korle Vista Medical Centre",
        category: "Hospital",
        contactName: "Dr. Kofi Owusu",
        phone: "+233 20 444 2211",
        email: "procurement@korlevista.gh",
        address: "Korle Bu, Accra",
        tin: "C0007654321",
        creditLimit: 500000,
        paymentTerms: "Net 30",
        notes: "",
        active: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
      {
        id: "cus-apex",
        code: "TLB-CUS-0003",
        name: "Apex Analytical Labs",
        category: "Laboratory",
        contactName: "Efua Boateng",
        phone: "+233 27 333 8899",
        email: "orders@apexlabs.gh",
        address: "Community 5, Tema",
        creditLimit: 180000,
        paymentTerms: "Net 15",
        active: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
    ],
    suppliers: [
      {
        id: "sup-ningbo",
        code: "TLB-VEN-0001",
        name: "Ningbo Industrial Chem",
        category: "Chemical",
        contactName: "Li Wei",
        phone: "+86 574 8888 1200",
        email: "export@ningbochem.cn",
        address: "Beilun District, Ningbo, China",
        tin: "CN91330200MA2",
        paymentTerms: "Net 45",
        notes: "Preferred sodium hydroxide and caustic imports via Tema.",
        active: true,
        preferred: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
      {
        id: "sup-tema-drum",
        code: "TLB-VEN-0002",
        name: "Tema Drum Works",
        category: "Packaging",
        contactName: "Yaw Boateng",
        phone: "+233 30 320 4410",
        email: "sales@temadrum.gh",
        address: "Heavy Industrial Area, Tema, Ghana",
        tin: "C0009988776",
        paymentTerms: "Net 30",
        notes: "HDPE drums and IBC cages for finished goods.",
        active: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
      {
        id: "sup-accra-lab",
        code: "TLB-VEN-0003",
        name: "Accra Lab Glass Ltd",
        category: "Equipment",
        contactName: "Nana Adjei",
        phone: "+233 24 111 7788",
        email: "orders@accralabglass.gh",
        address: "Ring Road Central, Accra",
        paymentTerms: "COD",
        notes: "Inactive alternate for assay glassware.",
        active: false,
        createdAt: THIS_YEAR,
        updatedAt: THIS_YEAR,
      },
    ],
    supplierPurchaseOrders: [
      {
        id: "spo-today",
        number: "TLB-PO-2609-00001",
        supplierId: "sup-ningbo",
        status: "In transit",
        orderDate: TODAY_AM,
        expectedDate: "2026-09-20",
        total: 186000,
        notes: "1×40ft container sodium hydroxide flakes.",
        createdAt: TODAY_AM,
        updatedAt: TODAY_AM,
      },
      {
        id: "spo-week",
        number: "TLB-PO-2609-00002",
        supplierId: "sup-tema-drum",
        status: "Open",
        orderDate: THIS_WEEK,
        expectedDate: "2026-09-12",
        total: 42000,
        notes: "200 HDPE drums for HCl packing.",
        createdAt: THIS_WEEK,
        updatedAt: THIS_WEEK,
      },
      {
        id: "spo-month",
        number: "TLB-PO-2609-00003",
        supplierId: "sup-ningbo",
        status: "Partially received",
        orderDate: EARLIER,
        expectedDate: "2026-09-15",
        total: 98000,
        notes: "Caustic liquor top-up — partial GRN posted.",
        createdAt: EARLIER,
        updatedAt: NOW,
      },
      {
        id: "spo-quarter",
        number: "TLB-PO-2608-00004",
        supplierId: "sup-tema-drum",
        status: "Received",
        orderDate: THIS_QUARTER,
        expectedDate: "2026-08-20",
        total: 27500,
        notes: "IBC cages for ethanol dispatch.",
        createdAt: THIS_QUARTER,
        updatedAt: PREV_MONTH_LATE,
      },
      {
        id: "spo-year",
        number: "TLB-PO-2603-00005",
        supplierId: "sup-accra-lab",
        status: "Cancelled",
        orderDate: THIS_YEAR,
        total: 8600,
        notes: "Cancelled — supplier went inactive.",
        createdAt: THIS_YEAR,
        updatedAt: THIS_YEAR,
      },
      {
        id: "spo-hcl-trace",
        number: "TLB-PO-2603-00006",
        supplierId: "sup-ningbo",
        status: "Partially received",
        orderDate: THIS_YEAR,
        expectedDate: "2026-08-01",
        total: 146400,
        notes: "HCl 32% import — traceability demo PO (Ningbo).",
        createdAt: THIS_YEAR,
        updatedAt: THIS_QUARTER,
      },
    ],
    supplierReceipts: [
      {
        id: "sgrn-today",
        number: "TLB-GRN-2609-00001",
        supplierId: "sup-tema-drum",
        purchaseOrderId: "spo-week",
        receivedAt: TODAY_AM,
        productId: "prod-hcl",
        quantity: 40,
        warehouseId: "wh-main",
        notes: "Partial drum intake against open PO.",
      },
      {
        id: "sgrn-week",
        number: "TLB-GRN-2609-00002",
        supplierId: "sup-ningbo",
        purchaseOrderId: "spo-month",
        receivedAt: THIS_WEEK,
        productId: "prod-chem-a",
        quantity: 12,
        warehouseId: "wh-main",
        notes: "First lot of caustic liquor.",
      },
      {
        id: "sgrn-month",
        number: "TLB-GRN-2609-00003",
        supplierId: "sup-ningbo",
        purchaseOrderId: "spo-month",
        receivedAt: EARLIER,
        productId: "prod-chem-b",
        quantity: 8,
        warehouseId: "wh-main",
        notes: "Companion chemical receipt.",
      },
      {
        id: "sgrn-prev",
        number: "TLB-GRN-2608-00004",
        supplierId: "sup-tema-drum",
        purchaseOrderId: "spo-quarter",
        receivedAt: PREV_MONTH_LATE,
        productId: "prod-eth",
        quantity: 50,
        warehouseId: "wh-factory",
        notes: "Full IBC cage receipt.",
      },
    ],
    supplierPayments: [
      {
        id: "spay-today",
        number: "TLB-SPAY-2609-00001",
        supplierId: "sup-tema-drum",
        purchaseOrderId: "spo-week",
        paymentDate: TODAY_AM,
        amount: 15000,
        method: "Mobile Money",
        notes: "Deposit on open drum PO.",
      },
      {
        id: "spay-week",
        number: "TLB-SPAY-2609-00002",
        supplierId: "sup-ningbo",
        purchaseOrderId: "spo-month",
        paymentDate: THIS_WEEK,
        amount: 45000,
        method: "Bank Transfer",
        notes: "Progress payment on caustic PO.",
      },
      {
        id: "spay-month",
        number: "TLB-SPAY-2609-00003",
        supplierId: "sup-ningbo",
        purchaseOrderId: "spo-today",
        paymentDate: EARLIER,
        amount: 60000,
        method: "Bank Transfer",
        notes: "LC-related advance for container.",
      },
      {
        id: "spay-prev",
        number: "TLB-SPAY-2608-00004",
        supplierId: "sup-tema-drum",
        purchaseOrderId: "spo-quarter",
        paymentDate: PREV_MONTH_LATE,
        amount: 27500,
        method: "Cheque",
        notes: "Settlement on received IBC PO.",
      },
    ],
    orders: [
      {
        id: "ord-phase30",
        number: "TLB-ORD-2609-00101",
        customerId: "cus-demo",
        customerPoNumber: "DCL-PO-8841",
        status: "Confirmed",
        orderDate: EARLIER,
        requiredDate: "2026-09-10",
        notes: "Phase 30 scenario: Chemical A=4, B=10. Stock starts A=2, B=25.",
        confirmedAt: EARLIER,
        createdAt: EARLIER,
        updatedAt: NOW,
        createdBy: "TLB Owner",
      },
      {
        id: "ord-today",
        number: "TLB-ORD-2609-00102",
        customerId: "cus-korle",
        customerPoNumber: "KV-PO-2201",
        status: "Confirmed",
        orderDate: TODAY_AM,
        requiredDate: "2026-09-11",
        notes: "Same-day HCl top-up for theatre stores.",
        confirmedAt: TODAY_AM,
        createdAt: TODAY_AM,
        updatedAt: TODAY_AM,
        createdBy: "TLB Owner",
      },
      {
        id: "ord-week",
        number: "TLB-ORD-2609-00103",
        customerId: "cus-apex",
        customerPoNumber: "AAL-PO-5510",
        status: "Ready for Supply",
        orderDate: THIS_WEEK,
        requiredDate: "2026-09-12",
        notes: "Ethanol drums for weekly lab schedule.",
        confirmedAt: THIS_WEEK,
        createdAt: THIS_WEEK,
        updatedAt: THIS_WEEK,
        createdBy: "TLB Owner",
      },
      {
        id: "ord-quarter",
        number: "TLB-ORD-2608-00104",
        customerId: "cus-korle",
        customerPoNumber: "KV-PO-2099",
        status: "Partially Supplied",
        orderDate: THIS_QUARTER,
        requiredDate: "2026-08-28",
        notes: "August restock — still partially open.",
        confirmedAt: THIS_QUARTER,
        createdAt: THIS_QUARTER,
        updatedAt: EARLIER,
        createdBy: "TLB Owner",
      },
      {
        id: "ord-year",
        number: "TLB-ORD-2603-00105",
        customerId: "cus-apex",
        customerPoNumber: "AAL-PO-4402",
        status: "Fully Supplied",
        orderDate: THIS_YEAR,
        requiredDate: "2026-03-25",
        notes: "Q1 solvent campaign — fully supplied.",
        confirmedAt: THIS_YEAR,
        createdAt: THIS_YEAR,
        updatedAt: THIS_YEAR,
        createdBy: "TLB Owner",
      },
    ],
    orderLines: [
      {
        id: "ol-a",
        orderId: "ord-phase30",
        productId: "prod-chem-a",
        warehouseId: "wh-main",
        orderedQty: 4,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 1850,
        lineStatus: "Awaiting Stock",
      },
      {
        id: "ol-b",
        orderId: "ord-phase30",
        productId: "prod-chem-b",
        warehouseId: "wh-main",
        orderedQty: 10,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 920,
        lineStatus: "Ready",
      },
      {
        id: "ol-today-hcl",
        orderId: "ord-today",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        orderedQty: 6,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 640,
        lineStatus: "Ready",
      },
      {
        id: "ol-week-eth",
        orderId: "ord-week",
        productId: "prod-eth",
        warehouseId: "wh-main",
        orderedQty: 12,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 1250,
        lineStatus: "Ready",
      },
      {
        id: "ol-qtr-hcl",
        orderId: "ord-quarter",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        orderedQty: 40,
        suppliedQty: 20,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 640,
        lineStatus: "Partially Supplied",
      },
      {
        id: "ol-year-eth",
        orderId: "ord-year",
        productId: "prod-eth",
        warehouseId: "wh-main",
        orderedQty: 30,
        suppliedQty: 30,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 1250,
        lineStatus: "Fully Supplied",
      },
    ],
    supplies: [],
    supplyLines: [],
    invoices: [],
    invoiceLines: [],
    /**
     * Seed collections dated across periods so dashboard “collected sales”
     * KPIs change when Today / Week / Month / Previous Month / custom ranges are selected.
     * Receipts without a linked payment count via amountPaid; payments are primary.
     */
    receipts: [
      {
        id: "rct-sep-cash",
        number: "TLB-RCT-2609-00101",
        customerId: "cus-demo",
        orderId: "ord-phase30",
        receiptDate: EARLIER,
        paymentMethod: "Cash",
        amount: 4200,
        amountPaid: 4200,
        balance: 0,
        processedBy: "TLB Owner",
        notes: "Partial COD collection on open Phase 30 order.",
        createdAt: EARLIER,
      },
      {
        id: "rct-aug-covered",
        number: "TLB-RCT-2608-00102",
        customerId: "cus-korle",
        orderId: "ord-quarter",
        receiptDate: THIS_QUARTER,
        paymentMethod: "Bank Transfer",
        amount: 12800,
        amountPaid: 12800,
        balance: 0,
        processedBy: "TLB Owner",
        notes: "Covered by linked payment — not double-counted in collections.",
        createdAt: THIS_QUARTER,
      },
    ],
    receiptLines: [],
    deliveries: [],
    deliveryItems: [],
    payments: [
      {
        id: "pay-today",
        number: "TLB-PAY-2609-00101",
        customerId: "cus-korle",
        orderId: "ord-today",
        paymentDate: TODAY_AM,
        method: "Mobile Money",
        amount: 3840,
        reference: "MTN-99021",
        recordedBy: "TLB Owner",
        notes: "Same-day HCl collection.",
        createdAt: TODAY_AM,
      },
      {
        id: "pay-week",
        number: "TLB-PAY-2609-00102",
        customerId: "cus-apex",
        orderId: "ord-week",
        paymentDate: THIS_WEEK,
        method: "Bank Transfer",
        amount: 15000,
        reference: "GTB-88412",
        recordedBy: "TLB Owner",
        notes: "Weekly ethanol deposit.",
        createdAt: THIS_WEEK,
      },
      {
        id: "pay-month",
        number: "TLB-PAY-2609-00103",
        customerId: "cus-demo",
        orderId: "ord-phase30",
        paymentDate: EARLIER,
        method: "Cheque",
        amount: 8500,
        reference: "CHQ-4410",
        recordedBy: "TLB Owner",
        notes: "Early-month collection on Phase 30.",
        createdAt: EARLIER,
      },
      {
        id: "pay-prev-month",
        number: "TLB-PAY-2608-00104",
        customerId: "cus-korle",
        orderId: "ord-quarter",
        receiptId: "rct-aug-covered",
        paymentDate: PREV_MONTH_LATE,
        method: "Bank Transfer",
        amount: 12800,
        reference: "GTB-77102",
        recordedBy: "TLB Owner",
        notes: "August collection linked to receipt.",
        createdAt: PREV_MONTH_LATE,
      },
      {
        id: "pay-year",
        number: "TLB-PAY-2603-00105",
        customerId: "cus-apex",
        orderId: "ord-year",
        paymentDate: THIS_YEAR,
        method: "Cash",
        amount: 37500,
        reference: "CASH-Q1",
        recordedBy: "TLB Owner",
        notes: "Q1 solvent campaign settlement.",
        createdAt: THIS_YEAR,
      },
    ],
    notifications: [],
    reservations: [],
    catalogDeletions: [],
    catalogPurgedIds: [],
    audit: [
      {
        id: "aud-1",
        at: EARLIER,
        actor: "TLB Owner",
        action: "order.created",
        entityType: "customer_purchase_order",
        entityId: "ord-phase30",
        summary: "Created customer order TLB-ORD-2609-00101 for Demo Chemical Labs.",
      },
      {
        id: "aud-2",
        at: EARLIER,
        actor: "TLB Owner",
        action: "order.confirmed",
        entityType: "customer_purchase_order",
        entityId: "ord-phase30",
        summary: "Confirmed TLB-ORD-2609-00101.",
      },
    ],
  };
}
