import { createSystemRoles, OWNER_USER_ID, SYSTEM_ROLE_IDS } from "../domain/permissions";
import type { TlbState } from "../domain/types";
import { DEFAULT_AGEING, DEFAULT_COMPANY, DEFAULT_VAT } from "./migrate";

const NOW = "2026-09-09T09:00:00.000Z";
const EARLIER = "2026-09-02T10:00:00.000Z";
/** Extra commercial dates so dashboard period filters diverge visibly. */
const TODAY_AM = "2026-09-09T08:15:00.000Z";
const THIS_WEEK = "2026-09-08T11:30:00.000Z";
const THIS_QUARTER = "2026-08-14T09:00:00.000Z";
const PREV_MONTH_LATE = "2026-08-28T14:20:00.000Z";
const THIS_YEAR = "2026-03-18T10:00:00.000Z";

/** Seed includes Phase 30 Chemical A/B scenario ready to demo. */
export function createSeedState(): TlbState {
  const roles = createSystemRoles();
  return {
    version: 7,
    currentUserId: OWNER_USER_ID,
    currentUser: "TLB Owner",
    currentRoleId: SYSTEM_ROLE_IDS.Owner,
    currentRole: "Owner",
    roles,
    users: [
      {
        id: OWNER_USER_ID,
        name: "TLB Owner",
        email: "owner@tlb.gh",
        roleId: SYSTEM_ROLE_IDS.Owner,
        active: true,
      },
      {
        id: "user-sales",
        name: "Ama Mensah",
        email: "sales@tlb.gh",
        roleId: SYSTEM_ROLE_IDS.Sales,
        active: true,
      },
      {
        id: "user-warehouse",
        name: "Kofi Boateng",
        email: "warehouse@tlb.gh",
        roleId: SYSTEM_ROLE_IDS.Warehouse,
        active: true,
      },
      {
        id: "user-finance",
        name: "Efua Addo",
        email: "finance@tlb.gh",
        roleId: SYSTEM_ROLE_IDS.Finance,
        active: true,
      },
      {
        id: "user-manager",
        name: "Yaw Mensah",
        email: "manager@tlb.gh",
        roleId: SYSTEM_ROLE_IDS.Manager,
        active: true,
      },
    ],
    ageing: { ...DEFAULT_AGEING },
    company: { ...DEFAULT_COMPANY },
    vatRates: DEFAULT_VAT.map((v) => ({ ...v })),
    counters: {
      order: 5,
      supply: 0,
      customer: 3,
      supplier: 3,
      supplierPo: 5,
      supplierReceipt: 4,
      supplierPayment: 4,
      invoice: 0,
      receipt: 2,
      delivery: 0,
      payment: 5,
    },
    warehouses: [
      {
        id: "wh-main",
        code: "MAIN",
        name: "Main Warehouse",
        location: "Tema · bonded chemicals",
        active: true,
      },
      {
        id: "wh-factory",
        code: "FACTORY",
        name: "Factory Store",
        location: "Production floor · WIP",
        active: true,
      },
    ],
    products: [
      {
        id: "prod-chem-a",
        sku: "CHEM-A",
        name: "Chemical A",
        unit: "drums",
        category: "Raw chemical",
        active: true,
      },
      {
        id: "prod-chem-b",
        sku: "CHEM-B",
        name: "Chemical B",
        unit: "drums",
        category: "Raw chemical",
        active: true,
      },
      {
        id: "prod-hcl",
        sku: "CHEM-001",
        name: "Hydrochloric Acid 32%",
        unit: "drums",
        category: "Acid",
        active: true,
      },
      {
        id: "prod-eth",
        sku: "CHEM-014",
        name: "Ethanol 96%",
        unit: "drums",
        category: "Solvent",
        active: true,
      },
    ],
    stock: [
      { id: "stk-a-main", productId: "prod-chem-a", warehouseId: "wh-main", physicalQty: 2, reservedQty: 0 },
      { id: "stk-b-main", productId: "prod-chem-b", warehouseId: "wh-main", physicalQty: 25, reservedQty: 0 },
      { id: "stk-hcl-main", productId: "prod-hcl", warehouseId: "wh-main", physicalQty: 240, reservedQty: 12 },
      { id: "stk-eth-main", productId: "prod-eth", warehouseId: "wh-main", physicalQty: 48, reservedQty: 0 },
      { id: "stk-hcl-fac", productId: "prod-hcl", warehouseId: "wh-factory", physicalQty: 40, reservedQty: 0 },
    ],
    customers: [
      {
        id: "cus-demo",
        code: "TLB-CUS-0001",
        name: "Demo Chemical Labs",
        category: "Laboratory",
        contactName: "Ama Mensah",
        phone: "+233 24 555 0101",
        email: "ama@demochem.gh",
        address: "12 Spintex Road, Accra",
        tin: "C0001234567",
        creditLimit: 250000,
        paymentTerms: "Net 30",
        notes: "Phase 30 demo customer for partial supply workflow.",
        active: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
      {
        id: "cus-korle",
        code: "TLB-CUS-0002",
        name: "Korle Vista Medical Centre",
        category: "Hospital",
        contactName: "Dr. Kofi Owusu",
        phone: "+233 20 444 2211",
        email: "procurement@korlevista.gh",
        address: "Korle Bu, Accra",
        tin: "C0007654321",
        creditLimit: 500000,
        paymentTerms: "Net 30",
        notes: "",
        active: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
      {
        id: "cus-apex",
        code: "TLB-CUS-0003",
        name: "Apex Analytical Labs",
        category: "Laboratory",
        contactName: "Efua Boateng",
        phone: "+233 27 333 8899",
        email: "orders@apexlabs.gh",
        address: "Community 5, Tema",
        creditLimit: 180000,
        paymentTerms: "Net 15",
        active: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
    ],
    suppliers: [
      {
        id: "sup-ningbo",
        code: "TLB-VEN-0001",
        name: "Ningbo Industrial Chem",
        category: "Chemical",
        contactName: "Li Wei",
        phone: "+86 574 8888 1200",
        email: "export@ningbochem.cn",
        address: "Beilun District, Ningbo, China",
        tin: "CN91330200MA2",
        paymentTerms: "Net 45",
        notes: "Preferred sodium hydroxide and caustic imports via Tema.",
        active: true,
        preferred: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
      {
        id: "sup-tema-drum",
        code: "TLB-VEN-0002",
        name: "Tema Drum Works",
        category: "Packaging",
        contactName: "Yaw Boateng",
        phone: "+233 30 320 4410",
        email: "sales@temadrum.gh",
        address: "Heavy Industrial Area, Tema, Ghana",
        tin: "C0009988776",
        paymentTerms: "Net 30",
        notes: "HDPE drums and IBC cages for finished goods.",
        active: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
      {
        id: "sup-accra-lab",
        code: "TLB-VEN-0003",
        name: "Accra Lab Glass Ltd",
        category: "Equipment",
        contactName: "Nana Adjei",
        phone: "+233 24 111 7788",
        email: "orders@accralabglass.gh",
        address: "Ring Road Central, Accra",
        paymentTerms: "COD",
        notes: "Inactive alternate for assay glassware.",
        active: false,
        createdAt: THIS_YEAR,
        updatedAt: THIS_YEAR,
      },
    ],
    supplierPurchaseOrders: [
      {
        id: "spo-today",
        number: "TLB-PO-2609-00001",
        supplierId: "sup-ningbo",
        status: "In transit",
        orderDate: TODAY_AM,
        expectedDate: "2026-09-20",
        total: 186000,
        notes: "1×40ft container sodium hydroxide flakes.",
        createdAt: TODAY_AM,
        updatedAt: TODAY_AM,
      },
      {
        id: "spo-week",
        number: "TLB-PO-2609-00002",
        supplierId: "sup-tema-drum",
        status: "Open",
        orderDate: THIS_WEEK,
        expectedDate: "2026-09-12",
        total: 42000,
        notes: "200 HDPE drums for HCl packing.",
        createdAt: THIS_WEEK,
        updatedAt: THIS_WEEK,
      },
      {
        id: "spo-month",
        number: "TLB-PO-2609-00003",
        supplierId: "sup-ningbo",
        status: "Partially received",
        orderDate: EARLIER,
        expectedDate: "2026-09-15",
        total: 98000,
        notes: "Caustic liquor top-up — partial GRN posted.",
        createdAt: EARLIER,
        updatedAt: NOW,
      },
      {
        id: "spo-quarter",
        number: "TLB-PO-2608-00004",
        supplierId: "sup-tema-drum",
        status: "Received",
        orderDate: THIS_QUARTER,
        expectedDate: "2026-08-20",
        total: 27500,
        notes: "IBC cages for ethanol dispatch.",
        createdAt: THIS_QUARTER,
        updatedAt: PREV_MONTH_LATE,
      },
      {
        id: "spo-year",
        number: "TLB-PO-2603-00005",
        supplierId: "sup-accra-lab",
        status: "Cancelled",
        orderDate: THIS_YEAR,
        total: 8600,
        notes: "Cancelled — supplier went inactive.",
        createdAt: THIS_YEAR,
        updatedAt: THIS_YEAR,
      },
    ],
    supplierReceipts: [
      {
        id: "sgrn-today",
        number: "TLB-GRN-2609-00001",
        supplierId: "sup-tema-drum",
        purchaseOrderId: "spo-week",
        receivedAt: TODAY_AM,
        productId: "prod-hcl",
        quantity: 40,
        warehouseId: "wh-main",
        notes: "Partial drum intake against open PO.",
      },
      {
        id: "sgrn-week",
        number: "TLB-GRN-2609-00002",
        supplierId: "sup-ningbo",
        purchaseOrderId: "spo-month",
        receivedAt: THIS_WEEK,
        productId: "prod-chem-a",
        quantity: 12,
        warehouseId: "wh-main",
        notes: "First lot of caustic liquor.",
      },
      {
        id: "sgrn-month",
        number: "TLB-GRN-2609-00003",
        supplierId: "sup-ningbo",
        purchaseOrderId: "spo-month",
        receivedAt: EARLIER,
        productId: "prod-chem-b",
        quantity: 8,
        warehouseId: "wh-main",
        notes: "Companion chemical receipt.",
      },
      {
        id: "sgrn-prev",
        number: "TLB-GRN-2608-00004",
        supplierId: "sup-tema-drum",
        purchaseOrderId: "spo-quarter",
        receivedAt: PREV_MONTH_LATE,
        productId: "prod-eth",
        quantity: 50,
        warehouseId: "wh-factory",
        notes: "Full IBC cage receipt.",
      },
    ],
    supplierPayments: [
      {
        id: "spay-today",
        number: "TLB-SPAY-2609-00001",
        supplierId: "sup-tema-drum",
        purchaseOrderId: "spo-week",
        paymentDate: TODAY_AM,
        amount: 15000,
        method: "Mobile Money",
        notes: "Deposit on open drum PO.",
      },
      {
        id: "spay-week",
        number: "TLB-SPAY-2609-00002",
        supplierId: "sup-ningbo",
        purchaseOrderId: "spo-month",
        paymentDate: THIS_WEEK,
        amount: 45000,
        method: "Bank Transfer",
        notes: "Progress payment on caustic PO.",
      },
      {
        id: "spay-month",
        number: "TLB-SPAY-2609-00003",
        supplierId: "sup-ningbo",
        purchaseOrderId: "spo-today",
        paymentDate: EARLIER,
        amount: 60000,
        method: "Bank Transfer",
        notes: "LC-related advance for container.",
      },
      {
        id: "spay-prev",
        number: "TLB-SPAY-2608-00004",
        supplierId: "sup-tema-drum",
        purchaseOrderId: "spo-quarter",
        paymentDate: PREV_MONTH_LATE,
        amount: 27500,
        method: "Cheque",
        notes: "Settlement on received IBC PO.",
      },
    ],
    orders: [
      {
        id: "ord-phase30",
        number: "TLB-ORD-2609-00001",
        customerId: "cus-demo",
        customerPoNumber: "DCL-PO-8841",
        status: "Confirmed",
        orderDate: EARLIER,
        requiredDate: "2026-09-10",
        notes: "Phase 30 scenario: Chemical A=4, B=10. Stock starts A=2, B=25.",
        confirmedAt: EARLIER,
        createdAt: EARLIER,
        updatedAt: NOW,
        createdBy: "TLB Owner",
      },
      {
        id: "ord-today",
        number: "TLB-ORD-2609-00002",
        customerId: "cus-korle",
        customerPoNumber: "KV-PO-2201",
        status: "Confirmed",
        orderDate: TODAY_AM,
        requiredDate: "2026-09-11",
        notes: "Same-day HCl top-up for theatre stores.",
        confirmedAt: TODAY_AM,
        createdAt: TODAY_AM,
        updatedAt: TODAY_AM,
        createdBy: "TLB Owner",
      },
      {
        id: "ord-week",
        number: "TLB-ORD-2609-00003",
        customerId: "cus-apex",
        customerPoNumber: "AAL-PO-5510",
        status: "Ready for Supply",
        orderDate: THIS_WEEK,
        requiredDate: "2026-09-12",
        notes: "Ethanol drums for weekly lab schedule.",
        confirmedAt: THIS_WEEK,
        createdAt: THIS_WEEK,
        updatedAt: THIS_WEEK,
        createdBy: "TLB Owner",
      },
      {
        id: "ord-quarter",
        number: "TLB-ORD-2608-00004",
        customerId: "cus-korle",
        customerPoNumber: "KV-PO-2099",
        status: "Partially Supplied",
        orderDate: THIS_QUARTER,
        requiredDate: "2026-08-28",
        notes: "August restock — still partially open.",
        confirmedAt: THIS_QUARTER,
        createdAt: THIS_QUARTER,
        updatedAt: EARLIER,
        createdBy: "TLB Owner",
      },
      {
        id: "ord-year",
        number: "TLB-ORD-2603-00005",
        customerId: "cus-apex",
        customerPoNumber: "AAL-PO-4402",
        status: "Fully Supplied",
        orderDate: THIS_YEAR,
        requiredDate: "2026-03-25",
        notes: "Q1 solvent campaign — fully supplied.",
        confirmedAt: THIS_YEAR,
        createdAt: THIS_YEAR,
        updatedAt: THIS_YEAR,
        createdBy: "TLB Owner",
      },
    ],
    orderLines: [
      {
        id: "ol-a",
        orderId: "ord-phase30",
        productId: "prod-chem-a",
        warehouseId: "wh-main",
        orderedQty: 4,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 1850,
        lineStatus: "Awaiting Stock",
      },
      {
        id: "ol-b",
        orderId: "ord-phase30",
        productId: "prod-chem-b",
        warehouseId: "wh-main",
        orderedQty: 10,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 920,
        lineStatus: "Ready",
      },
      {
        id: "ol-today-hcl",
        orderId: "ord-today",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        orderedQty: 6,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 640,
        lineStatus: "Ready",
      },
      {
        id: "ol-week-eth",
        orderId: "ord-week",
        productId: "prod-eth",
        warehouseId: "wh-main",
        orderedQty: 12,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 1250,
        lineStatus: "Ready",
      },
      {
        id: "ol-qtr-hcl",
        orderId: "ord-quarter",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        orderedQty: 40,
        suppliedQty: 20,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 640,
        lineStatus: "Partially Supplied",
      },
      {
        id: "ol-year-eth",
        orderId: "ord-year",
        productId: "prod-eth",
        warehouseId: "wh-main",
        orderedQty: 30,
        suppliedQty: 30,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 1250,
        lineStatus: "Fully Supplied",
      },
    ],
    supplies: [],
    supplyLines: [],
    invoices: [],
    invoiceLines: [],
    /**
     * Seed collections dated across periods so dashboard “collected sales”
     * KPIs change when Today / Week / Month / Previous Month / custom ranges are selected.
     * Receipts without a linked payment count via amountPaid; payments are primary.
     */
    receipts: [
      {
        id: "rct-sep-cash",
        number: "TLB-RCT-2609-00001",
        customerId: "cus-demo",
        orderId: "ord-phase30",
        receiptDate: EARLIER,
        paymentMethod: "Cash",
        amount: 4200,
        amountPaid: 4200,
        balance: 0,
        processedBy: "TLB Owner",
        notes: "Partial COD collection on open Phase 30 order.",
        createdAt: EARLIER,
      },
      {
        id: "rct-aug-covered",
        number: "TLB-RCT-2608-00002",
        customerId: "cus-korle",
        orderId: "ord-quarter",
        receiptDate: THIS_QUARTER,
        paymentMethod: "Bank Transfer",
        amount: 12800,
        amountPaid: 12800,
        balance: 0,
        processedBy: "TLB Owner",
        notes: "Covered by linked payment — not double-counted in collections.",
        createdAt: THIS_QUARTER,
      },
    ],
    receiptLines: [],
    deliveries: [],
    deliveryItems: [],
    payments: [
      {
        id: "pay-today",
        number: "TLB-PAY-2609-00001",
        customerId: "cus-korle",
        orderId: "ord-today",
        paymentDate: TODAY_AM,
        method: "Mobile Money",
        amount: 3840,
        reference: "MTN-99021",
        recordedBy: "TLB Owner",
        notes: "Same-day HCl collection.",
        createdAt: TODAY_AM,
      },
      {
        id: "pay-week",
        number: "TLB-PAY-2609-00002",
        customerId: "cus-apex",
        orderId: "ord-week",
        paymentDate: THIS_WEEK,
        method: "Bank Transfer",
        amount: 15000,
        reference: "GTB-88412",
        recordedBy: "TLB Owner",
        notes: "Weekly ethanol deposit.",
        createdAt: THIS_WEEK,
      },
      {
        id: "pay-month",
        number: "TLB-PAY-2609-00003",
        customerId: "cus-demo",
        orderId: "ord-phase30",
        paymentDate: EARLIER,
        method: "Cheque",
        amount: 8500,
        reference: "CHQ-4410",
        recordedBy: "TLB Owner",
        notes: "Early-month collection on Phase 30.",
        createdAt: EARLIER,
      },
      {
        id: "pay-prev-month",
        number: "TLB-PAY-2608-00004",
        customerId: "cus-korle",
        orderId: "ord-quarter",
        receiptId: "rct-aug-covered",
        paymentDate: PREV_MONTH_LATE,
        method: "Bank Transfer",
        amount: 12800,
        reference: "GTB-77102",
        recordedBy: "TLB Owner",
        notes: "August collection linked to receipt.",
        createdAt: PREV_MONTH_LATE,
      },
      {
        id: "pay-year",
        number: "TLB-PAY-2603-00005",
        customerId: "cus-apex",
        orderId: "ord-year",
        paymentDate: THIS_YEAR,
        method: "Cash",
        amount: 37500,
        reference: "CASH-Q1",
        recordedBy: "TLB Owner",
        notes: "Q1 solvent campaign settlement.",
        createdAt: THIS_YEAR,
      },
    ],
    notifications: [],
    reservations: [],
    catalogDeletions: [],
    catalogPurgedIds: [],
    audit: [
      {
        id: "aud-1",
        at: EARLIER,
        actor: "TLB Owner",
        action: "order.created",
        entityType: "customer_purchase_order",
        entityId: "ord-phase30",
        summary: "Created customer order TLB-ORD-2609-00001 for Demo Chemical Labs.",
      },
      {
        id: "aud-2",
        at: EARLIER,
        actor: "TLB Owner",
        action: "order.confirmed",
        entityType: "customer_purchase_order",
        entityId: "ord-phase30",
        summary: "Confirmed TLB-ORD-2609-00001.",
      },
    ],
  };
}
