import type { TlbState } from "../domain/types";
import { DEFAULT_AGEING, DEFAULT_COMPANY, DEFAULT_VAT } from "./migrate";

const NOW = "2026-09-09T09:00:00.000Z";
const EARLIER = "2026-09-02T10:00:00.000Z";
/** Extra commercial dates so dashboard period filters diverge visibly. */
const TODAY_AM = "2026-09-09T08:15:00.000Z";
const THIS_WEEK = "2026-09-08T11:30:00.000Z";
const THIS_QUARTER = "2026-08-14T09:00:00.000Z";
const THIS_YEAR = "2026-03-18T10:00:00.000Z";

/** Seed includes Phase 30 Chemical A/B scenario ready to demo. */
export function createSeedState(): TlbState {
  return {
    version: 2,
    currentUser: "Kwame Asare",
    currentRole: "Manager",
    ageing: { ...DEFAULT_AGEING },
    company: { ...DEFAULT_COMPANY },
    vatRates: DEFAULT_VAT.map((v) => ({ ...v })),
    counters: { order: 5, supply: 0, customer: 3, invoice: 0, receipt: 0, delivery: 0, payment: 0 },
    warehouses: [
      {
        id: "wh-main",
        code: "MAIN",
        name: "Main Warehouse",
        location: "Tema · bonded chemicals",
        active: true,
      },
      {
        id: "wh-factory",
        code: "FACTORY",
        name: "Factory Store",
        location: "Production floor · WIP",
        active: true,
      },
    ],
    products: [
      {
        id: "prod-chem-a",
        sku: "CHEM-A",
        name: "Chemical A",
        unit: "drums",
        category: "Raw chemical",
        active: true,
      },
      {
        id: "prod-chem-b",
        sku: "CHEM-B",
        name: "Chemical B",
        unit: "drums",
        category: "Raw chemical",
        active: true,
      },
      {
        id: "prod-hcl",
        sku: "CHEM-001",
        name: "Hydrochloric Acid 32%",
        unit: "drums",
        category: "Acid",
        active: true,
      },
      {
        id: "prod-eth",
        sku: "CHEM-014",
        name: "Ethanol 96%",
        unit: "drums",
        category: "Solvent",
        active: true,
      },
    ],
    stock: [
      { id: "stk-a-main", productId: "prod-chem-a", warehouseId: "wh-main", physicalQty: 2, reservedQty: 0 },
      { id: "stk-b-main", productId: "prod-chem-b", warehouseId: "wh-main", physicalQty: 25, reservedQty: 0 },
      { id: "stk-hcl-main", productId: "prod-hcl", warehouseId: "wh-main", physicalQty: 240, reservedQty: 12 },
      { id: "stk-eth-main", productId: "prod-eth", warehouseId: "wh-main", physicalQty: 48, reservedQty: 0 },
      { id: "stk-hcl-fac", productId: "prod-hcl", warehouseId: "wh-factory", physicalQty: 40, reservedQty: 0 },
    ],
    customers: [
      {
        id: "cus-demo",
        code: "TLB-CUS-0001",
        name: "Demo Chemical Labs",
        category: "Laboratory",
        contactName: "Ama Mensah",
        phone: "+233 24 555 0101",
        email: "ama@demochem.gh",
        address: "12 Spintex Road, Accra",
        tin: "C0001234567",
        creditLimit: 250000,
        paymentTerms: "Net 30",
        notes: "Phase 30 demo customer for partial supply workflow.",
        active: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
      {
        id: "cus-korle",
        code: "TLB-CUS-0002",
        name: "Korle Vista Medical Centre",
        category: "Hospital",
        contactName: "Dr. Kofi Owusu",
        phone: "+233 20 444 2211",
        email: "procurement@korlevista.gh",
        address: "Korle Bu, Accra",
        tin: "C0007654321",
        creditLimit: 500000,
        paymentTerms: "Net 30",
        notes: "",
        active: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
      {
        id: "cus-apex",
        code: "TLB-CUS-0003",
        name: "Apex Analytical Labs",
        category: "Laboratory",
        contactName: "Efua Boateng",
        phone: "+233 27 333 8899",
        email: "orders@apexlabs.gh",
        address: "Community 5, Tema",
        creditLimit: 180000,
        paymentTerms: "Net 15",
        active: true,
        createdAt: EARLIER,
        updatedAt: EARLIER,
      },
    ],
    orders: [
      {
        id: "ord-phase30",
        number: "TLB-ORD-2609-00001",
        customerId: "cus-demo",
        customerPoNumber: "DCL-PO-8841",
        status: "Confirmed",
        orderDate: EARLIER,
        requiredDate: "2026-09-10",
        notes: "Phase 30 scenario: Chemical A=4, B=10. Stock starts A=2, B=25.",
        confirmedAt: EARLIER,
        createdAt: EARLIER,
        updatedAt: NOW,
        createdBy: "Kwame Asare",
      },
      {
        id: "ord-today",
        number: "TLB-ORD-2609-00002",
        customerId: "cus-korle",
        customerPoNumber: "KV-PO-2201",
        status: "Confirmed",
        orderDate: TODAY_AM,
        requiredDate: "2026-09-11",
        notes: "Same-day HCl top-up for theatre stores.",
        confirmedAt: TODAY_AM,
        createdAt: TODAY_AM,
        updatedAt: TODAY_AM,
        createdBy: "Kwame Asare",
      },
      {
        id: "ord-week",
        number: "TLB-ORD-2609-00003",
        customerId: "cus-apex",
        customerPoNumber: "AAL-PO-5510",
        status: "Ready for Supply",
        orderDate: THIS_WEEK,
        requiredDate: "2026-09-12",
        notes: "Ethanol drums for weekly lab schedule.",
        confirmedAt: THIS_WEEK,
        createdAt: THIS_WEEK,
        updatedAt: THIS_WEEK,
        createdBy: "Kwame Asare",
      },
      {
        id: "ord-quarter",
        number: "TLB-ORD-2608-00004",
        customerId: "cus-korle",
        customerPoNumber: "KV-PO-2099",
        status: "Partially Supplied",
        orderDate: THIS_QUARTER,
        requiredDate: "2026-08-28",
        notes: "August restock — still partially open.",
        confirmedAt: THIS_QUARTER,
        createdAt: THIS_QUARTER,
        updatedAt: EARLIER,
        createdBy: "Kwame Asare",
      },
      {
        id: "ord-year",
        number: "TLB-ORD-2603-00005",
        customerId: "cus-apex",
        customerPoNumber: "AAL-PO-4402",
        status: "Fully Supplied",
        orderDate: THIS_YEAR,
        requiredDate: "2026-03-25",
        notes: "Q1 solvent campaign — fully supplied.",
        confirmedAt: THIS_YEAR,
        createdAt: THIS_YEAR,
        updatedAt: THIS_YEAR,
        createdBy: "Kwame Asare",
      },
    ],
    orderLines: [
      {
        id: "ol-a",
        orderId: "ord-phase30",
        productId: "prod-chem-a",
        warehouseId: "wh-main",
        orderedQty: 4,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 1850,
        lineStatus: "Awaiting Stock",
      },
      {
        id: "ol-b",
        orderId: "ord-phase30",
        productId: "prod-chem-b",
        warehouseId: "wh-main",
        orderedQty: 10,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 920,
        lineStatus: "Ready",
      },
      {
        id: "ol-today-hcl",
        orderId: "ord-today",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        orderedQty: 6,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 640,
        lineStatus: "Ready",
      },
      {
        id: "ol-week-eth",
        orderId: "ord-week",
        productId: "prod-eth",
        warehouseId: "wh-main",
        orderedQty: 12,
        suppliedQty: 0,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 1250,
        lineStatus: "Ready",
      },
      {
        id: "ol-qtr-hcl",
        orderId: "ord-quarter",
        productId: "prod-hcl",
        warehouseId: "wh-main",
        orderedQty: 40,
        suppliedQty: 20,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 640,
        lineStatus: "Partially Supplied",
      },
      {
        id: "ol-year-eth",
        orderId: "ord-year",
        productId: "prod-eth",
        warehouseId: "wh-main",
        orderedQty: 30,
        suppliedQty: 30,
        cancelledQty: 0,
        reservedQty: 0,
        unitPrice: 1250,
        lineStatus: "Fully Supplied",
      },
    ],
    supplies: [],
    supplyLines: [],
    invoices: [],
    invoiceLines: [],
    receipts: [],
    receiptLines: [],
    deliveries: [],
    deliveryItems: [],
    payments: [],
    notifications: [],
    reservations: [],
    audit: [
      {
        id: "aud-1",
        at: EARLIER,
        actor: "Kwame Asare",
        action: "order.created",
        entityType: "customer_purchase_order",
        entityId: "ord-phase30",
        summary: "Created customer order TLB-ORD-2609-00001 for Demo Chemical Labs.",
      },
      {
        id: "aud-2",
        at: EARLIER,
        actor: "Kwame Asare",
        action: "order.confirmed",
        entityType: "customer_purchase_order",
        entityId: "ord-phase30",
        summary: "Confirmed TLB-ORD-2609-00001.",
      },
    ],
  };
}
