/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as ApiInviteEmailRouteImport } from './routes/api/invite-email'
import { Route as ApiInviteSmsRouteImport } from './routes/api/invite-sms'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const ApiInviteEmailRoute = ApiInviteEmailRouteImport.update({
  id: '/api/invite-email',
  path: '/api/invite-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInviteSmsRoute = ApiInviteSmsRouteImport.update({
  id: '/api/invite-sms',
  path: '/api/invite-sms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/access': typeof AccessRoute
  '/profile': typeof AppProfileRoute
  '/api/invite-email': typeof ApiInviteEmailRoute
  '/api/invite-sms': typeof ApiInviteSmsRoute
}
export interface FileRoutesByTo {
  '/access': typeof AccessRoute
  '/profile': typeof AppProfileRoute
  '/api/invite-email': typeof ApiInviteEmailRoute
  '/api/invite-sms': typeof ApiInviteSmsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/access': typeof AccessRoute
  '/_app/profile': typeof AppProfileRoute
  '/api/invite-email': typeof ApiInviteEmailRoute
  '/api/invite-sms': typeof ApiInviteSmsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/access' | '/profile' | '/api/invite-email' | '/api/invite-sms'
  fileRoutesByTo: FileRoutesByTo
  to: '/access' | '/profile' | '/api/invite-email' | '/api/invite-sms' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/access'
    | '/_app/profile'
    | '/api/invite-email'
    | '/api/invite-sms'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AccessRoute: typeof AccessRoute
  ApiInviteEmailRoute: typeof ApiInviteEmailRoute
  ApiInviteSmsRoute: typeof ApiInviteSmsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/invite-email': {
      id: '/api/invite-email'
      path: '/api/invite-email'
      fullPath: '/api/invite-email'
      preLoaderRoute: typeof ApiInviteEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invite-sms': {
      id: '/api/invite-sms'
      path: '/api/invite-sms'
      fullPath: '/api/invite-sms'
      preLoaderRoute: typeof ApiInviteSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AccessRoute: AccessRoute,
  ApiInviteEmailRoute: ApiInviteEmailRoute,
  ApiInviteSmsRoute: ApiInviteSmsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
